name: Publish dev

on:
  push:
    branches:
      - dev

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 14' # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '14'

      - name: Install and link dependencies
        run: |
          yarn --cwd ./packages/ui-shared install --force
          yarn --cwd ./packages/ui-shared dev:prepare
          yarn build
          npx lerna bootstrap

      - name: 'Setup npm'
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          npx lerna publish from-git --dist-tag next --yes --canary
