name: Publish dev

on:
  push:
    branches:
      - dev

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 14' # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '14'

      - name: Install dependencies
        run: | # Install and link dependencies
          npx lerna bootstrap

      - name: 'Setup npm'
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: yarn publish:stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
