name: Publish dev

on:
  push:
    branches:
      - dev

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 14' # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '14'

      - name: Build ui shared
        run: yarn --cwd ./packages/ui-shared install --force && yarn --cwd ./packages/ui-shared dev:prepare

      - name: Install dependencies
        run: | # Install and link dependencies
          yarn build

      - name: Link dependencies
        run: | # Install and link dependencies
          npx lerna bootstrap

      - name: 'Setup npm'
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npx lerna publish --conventional-commits --conventional-graduate --preid beta --canary --dist-tag next --no-verify-access --yes --no-push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
